version: "3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /mydata/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  mysql8:
    container_name: mysql8       # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    #env_file: 设置环境变量文件
    #  - .env
    volumes:
      - /mydata/mysql/data:/var/lib/mysql"           # 挂载数据目录
      - /mydata/mysql/conf.d:/etc/mysql/conf.d"      # 挂载配置文件目录
      - /mydata/mysql/my.cnf:/etc/my.cnf
  redis:
    image: redis:6.2.6
    container_name: redis6
    restart: always
    volumes:
      - /mydata/redis/redis.conf:/etc/redis/redis.conf:ro
      - /mydata/redis/data:/data
      - /mydata/redis/logs:/logs
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379





networks:
  docker-compose-default:
    external: true